# Generated by Django 4.1.5 on 2023-03-01 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"verbose_name": "Critique", "verbose_name_plural": "Critiques"},
        ),
    ]
