# Generated by Django 4.1.5 on 2023-02-28 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_alter_review_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={},
        ),
    ]
