# Generated by Django 4.1.5 on 2023-03-01 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userfollows",
            options={
                "verbose_name": "Abonnement: abonné/suivi",
                "verbose_name_plural": "Abonnements: abonné/suivi",
            },
        ),
    ]
