# Generated by Django 4.1.5 on 2023-03-01 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_alter_userfollows_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userfollows",
            options={"verbose_name": "Abonnement: abonné/suivi"},
        ),
    ]
