# Generated by Django 4.1.5 on 2023-02-23 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"verbose_name": "Ticket"},
        ),
    ]
