# Generated by Django 4.1.5 on 2023-03-03 17:12

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_alter_ticket_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="JPEG",
                keep_meta=True,
                null=True,
                quality=100,
                scale=None,
                size=[200, 300],
                upload_to="",
            ),
        ),
    ]
