# Generated by Django 4.1.5 on 2023-02-28 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_alter_ticket_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={},
        ),
    ]
