# Generated by Django 4.1.5 on 2023-03-10 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0004_alter_ticket_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="time_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
