# Generated by Django 4.1.5 on 2023-03-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0005_alter_ticket_time_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="time_created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
